# Generated by Django 4.0.3 on 2022-06-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
